name: Deploy Azure Enterprise Scale Landing Zone
on:
  push:
      branches: [ main ]
  workflow_dispatch:
env:
  az_powershell_min_version: '9.6.0'

jobs:
  process-management-groups:
    uses: ./.github/workflows/1-process-management-groups.yml
    with: 
      az_powershell_min_version: '9.6.0'
