name: Process Management Groups

on:
  workflow_call:
    inputs:
      az_powershell_min_version:
        required: true
        type: string

jobs:
  deploy-management-groups:
    runs-on: [self-hosted, linux]
    
    env:
      az_powershell_min_version: ${{ inputs.az_powershell_min_version }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        name: Azure OIDC login
        with:         
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
      
      - shell: pwsh
        name: Ensure correct Az module is installed
        run: |
          if (Get-Module Az -ListAvailable | Where-Object { $_.Version -eq $env:az_powershell_min_version }) {
            Write-Host "Az module version $env:az_powershell_min_version is already installed"
            Import-Module Az -MinimumVersion $env:az_powershell_min_version
          }
          else {
              Write-Host "Az module version $env:az_powershell_min_version is going to be installed"
              Install-Module -Name Az -AllowClobber -Force -Scope CurrentUser -Repository PSGallery -MinimumVersion $env:az_powershell_min_version
          }
      
      - shell: pwsh
        name: Processing Subscriptions and Management Groups
        id: managementGroups
        run: |
          ./process-management-groups-structure.ps1
      
      - shell: pwsh
        name: Reading environment variables
        run: |
          Get-ChildItem env: | fl
          
      
      - uses: azure/powershell@v1
        name: Re-Reading all MGs
        with:
          inlineScript: |
            $TopManagementGroupResourceId = "${{ steps.managementGroups.outputs.Andor_MG_Resource_Id }}"
            $TopManagementGroupId = $TopManagementGroupResourceId.split("/")[-1]
            Get-AzManagementGroup -GroupName $TopManagementGroupId -Expand -Recurse
          azPSVersion: "latest"

    outputs:
          Andor_MG_Resource_Id: ${{ steps.managementGroups.outputs.Andor_MG_Resource_Id }}
          Platform_MG_Resource_Id: ${{ steps.managementGroups.outputs.Platform_MG_Resource_Id }}
          Connectivity_MG_Resource_Id: ${{ steps.managementGroups.outputs.Connectivity_MG_Resource_Id }}
          Identity_MG_Resource_Id: ${{ steps.managementGroups.outputs.Identity_MG_Resource_Id }}
          Management_MG_Resource_Id: ${{ steps.managementGroups.outputs.Management_MG_Resource_Id }}
          Landing_Zones_MG_Resource_Id: ${{ steps.managementGroups.outputs.Landing_Zones_MG_Resource_Id }}
          Corp_MG_Resource_Id: ${{ steps.managementGroups.outputs.Corp_MG_Resource_Id }}
          Online_MG_Resource_Id: ${{ steps.managementGroups.outputs.Online_MG_Resource_Id }}
          Decommisioned_MG_Resource_Id: ${{ steps.managementGroups.outputs.Decommisioned_MG_Resource_Id }}
          Sandbox_MG_Resource_Id: ${{ steps.managementGroups.outputs.Sandbox_MG_Resource_Id }}