name: Process Management Groups

on:
  workflow_call:
    inputs:
      az_powershell_min_version:
        required: true
        type: string

jobs:
  deploy-management-groups:
    runs-on: [self-hosted, linux]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        name: Azure OIDC login
        with:         
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
      
      - shell: pwsh
        name: Ensure correct Az module is installed
        run: |
          if (Get-Module Az -ListAvailable | Where-Object { $_.Version -eq $az_powershell_min_version }) {
            Write-Output "Az module version $az_powershell_min_version is already installed"
            Import-Module Az -MinimumVersion $az_powershell_min_version
          }
          else {
              Install-Module -Name Az -AllowClobber -Force -Scope CurrentUser -Repository PSGallery -MinimumVersion $az_powershell_min_version
          }